#pragma once

#include <wpr/parsers/Errors.hpp>
#include <wpr/parsers/Next.hpp>
#include <wpr/parsers/Opt.hpp>
#include <wpr/parsers/Seq.hpp>
#include <wpr/parsers/First.hpp>
#include <wpr/parsers/Transformer.hpp>
#include <wpr/parsers/ErrorTransformer.hpp>
#include <wpr/parsers/Satisfy.hpp>
#include <wpr/parsers/Handle.hpp>
#include <wpr/parsers/Repeat.hpp>
#include <wpr/parsers/Between.hpp>
#include <wpr/parsers/Select.hpp>
#include <wpr/parsers/OrElse.hpp>
#include <wpr/parsers/Panic.hpp>
#include <wpr/parsers/Catcher.hpp>
#include <wpr/parsers/ErrorBinder.hpp>
#include <wpr/parsers/Binder.hpp>
#include <wpr/parsers/Unit.hpp>
#include <wpr/parsers/Inverse.hpp>
#include <wpr/parsers/Switcher.hpp>
